# Gradient Calculation With Autograd

In [1]:
import torch

In [13]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2.0
print(z)

z = z.mean()
print("z.mean()", z)

z.backward()
print(x.grad)


tensor([1., 2., 3.], requires_grad=True)
tensor([3., 4., 5.], grad_fn=<AddBackward0>)
tensor([18., 32., 50.], grad_fn=<MulBackward0>)
z.mean() tensor(33.3333, grad_fn=<MeanBackward0>)
tensor([4.0000, 5.3333, 6.6667])


In [24]:
r = torch.rand(5, requires_grad=True)
print(r)

# r.requires_grad_(False)
# r = r.detach()

with torch.no_grad():
    y = r * r
    print(y)

tensor([0.3446, 0.0790, 0.1214, 0.2459, 0.5837], requires_grad=True)
tensor([0.1187, 0.0062, 0.0147, 0.0605, 0.3407])


In [26]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

   

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [29]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()  # !!!

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
