# Gradient Calculation With Autograd

https://www.youtube.com/watch?v=DbeIqrwb_dE&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=3

In [32]:
import torch

In [33]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2.0
print(z)

z = z.mean()
print("z.mean()", z)

z.backward()
print(x.grad)


tensor([1., 2., 3.], requires_grad=True)
tensor([3., 4., 5.], grad_fn=<AddBackward0>)
tensor([18., 32., 50.], grad_fn=<MulBackward0>)
z.mean() tensor(33.3333, grad_fn=<MeanBackward0>)
tensor([4.0000, 5.3333, 6.6667])


In [34]:
r = torch.rand(5, requires_grad=True)
print(r)

# r.requires_grad_(False)
# r = r.detach()

with torch.no_grad():
    y = r * r
    print(y)

tensor([0.6039, 0.9240, 0.4384, 0.9690, 0.2368], requires_grad=True)
tensor([0.3647, 0.8538, 0.1922, 0.9389, 0.0561])


In [35]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

   

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [36]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()  # !!!

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [37]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()


TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor