In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [4]:
# 3 dimensonale input = Bias,Anwesend A, Anwesend B
# 4 Inputvektoren
x = np.array([
    [1,0,0],
    [1,1,0],
    [1,0,1],
    [1,1,1],
])
print("Input Vectoren", x, " shape: ", x.shape)

Input Vectoren [[1 0 0]
 [1 1 0]
 [1 0 1]
 [1 1 1]]  shape:  (4, 3)


In [37]:
# Gewünschte Ergebniswerte
y = np.array([0,1,1,1])

In [38]:
# Heaviside - Funktiom
def heaviside(summe):
    if summe >= 0 :
        return 1
    else:
        return 0

In [47]:
def perceptron_eval(X, Y)-> float:
    gesamtfehler = 0

    # gewichte so wählen dass das OR - Problem gelöst werden kann
    weights = np.array([-1, 1, 1])

    for i, x in enumerate(X):
        summe = np.dot(weights,x)
        ergebnis = heaviside(summe)
        # Fehler
        fehler = np.abs(ergebnis - Y[i])
        gesamtfehler += fehler
        print("A = {}, B={}, gewuenschtes Ergebnis = {}, errechnetes Ergebnis = {}, Fehler = {}".format(x[1], x[2], Y[i], ergebnis, fehler))





In [48]:
gesamtfehler =  perceptron_eval(x,y)
print(gesamtfehler)

A = 0, B=0, gewuenschtes Ergebnis = 0, errechnetes Ergebnis = 0, Fehler = 0
A = 1, B=0, gewuenschtes Ergebnis = 1, errechnetes Ergebnis = 1, Fehler = 0
A = 0, B=1, gewuenschtes Ergebnis = 1, errechnetes Ergebnis = 1, Fehler = 0
A = 1, B=1, gewuenschtes Ergebnis = 1, errechnetes Ergebnis = 1, Fehler = 0
None
