In [1]:
x1, x2, x3 = 1, 2 , 3
bias = 0.1
w1 = .3
w2 = .5

x = [x1,x2,x3]
w = [bias, w1,w2]

print(x)
print(w)

[1, 2, 3]
[0.1, 0.3, 0.5]


In [2]:
z = 0
for i in range(len(x)):
    z += x[i] * w[i]
print(z)       

2.2


In [6]:

l = [xi * wi for xi, wi in zip(x,w)]
print(l)
z = sum(l)
print(z)
z = sum(xi * wi for xi, wi in zip(x,w))
print(z)

[0.1, 0.6, 1.5]
2.2
2.2


In [7]:
import numpy as np

In [15]:
x_vec, w_vec = np.array(x), np.array(w)

z = (x_vec.transpose()).dot(w_vec)
print(z)

z = x_vec.dot(w_vec)
print(z)

print(x_vec.T@w_vec)
print(x_vec@w_vec)

2.2
2.2
2.2
2.2


In [23]:
def generator():
    for i in range(10):
        if i%2:
            yield i


In [24]:
gen = generator()
v = np.fromiter(gen, dtype=np.int32)
v


array([1, 3, 5, 7, 9])

In [28]:
generator_expression = (i for i in range(20) if i % 2)
np.fromiter(generator_expression, dtype=int)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
m1 = np.ones((3,2))
m1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
m1.T

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
v1 = np.array([1,2,3])
v1@m1

array([6., 6.])