In [1]:
import numpy as np

In [2]:
def mathmul_forward(x,w):
    print(x.shape[1], w.shape[0])

    assert x.shape[1] == w.shape[0],   print("Fehler !!!")

    N = x * w
    return N

In [30]:
x =np.array([[1,2,3]])
w =np.array([[11,22,33]])

print(x.shape, w.shape)
print(x.shape[1], w.shape[0])
print("--------------------------------------")
w = w.T
print(x.shape[0], w.shape[0])
print(x.shape[1], w.shape[0])
print(x)
print(w)
print("--------------------------------------")
print("x.dot(w) = ", x.dot(w))
N = np.dot(x,w)
print("np.dot(x,w) = ", N )
#print(mathmul_forward(x,w))

(1, 3) (1, 3)
3 1
--------------------------------------
1 3
3 3
[[1 2 3]]
[[11]
 [22]
 [33]]
--------------------------------------
x.dot(w) =  [[154]]
np.dot(x,w) =  [[154]]


In [37]:
# Initialize arrays
arr = np.array([3, 1, 2])
arr1 = np.array([2, 4, 3])

#arr = arr.T
print(arr, arr1)
print(arr.shape)
print(arr1.shape)

# Get the dot product of 1-D arrays
arr2 = np.dot(arr, arr1)
print(arr2)


[3 1 2] [2 4 3]
(3,)
(3,)
16
